apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: expense
    namespace: expense
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/tags: Environment=dev,Project=expense
        alb.ingress.kubernetes.io/group.name: acavinash
spec:
  ingressClassName: alb
  rules:
  - host: "expense.acavinash.fun"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80